- name: Delete instance.cfg related to splunkUF
  file:
    state: absent
    path: "/opt/splunkforwarder/etc/instance.cfg"
  become_method: sudo

- name: Delete instance.cfg related to splunkUF
  file:
    state: absent
    path: "/opt/splunkforwarder/etc/system/local/server.conf"
  become_method: sudo
  
- name: restart splunk Universal forwarder 
  service:
    name: SplunkForwarder
    state: restarted
  become_method: sudo
