- name: Update and upgrade packages
  become: true
  apt:
    update_cache: yes
    upgrade: dist

- name: Install packages
  apt:
    name:
      - nfs-common
    state: present
  become: true          
