- name: Generate a random password
  command: "openssl rand -base64 8"
  register: random_password

- name: Generate a random password
  set_fact:
    generated_password: "{{ random_password.stdout|password_hash('sha512') }}"

- name: Set fact with IP address
  set_fact:
    ip_address: "{{ ansible_default_ipv4.address }}"

- name: Change root password
  user:
    name: root
    update_password: always
    password: "{{ generated_password }}"

- name: Print new root password
  debug:
    msg: "The new root password of {{ ip_address }} has been set to {{random_password.stdout}}"

#- name: Save output to file
#copy:
#content: "{{ ip_address }}   {{ random_password.stdout }}"
#dest: ./output.txt      
#delegate_to: localhost 

#- name: Append message to file
#lineinfile:
#create: yes
#path: ./passwords.txt  
#line: "{{ ip_address }}    {{ random_password.stdout }}"      
#delegate_to: localhost   
